api:
  port: 8080
db:
  encryption_key: ThirtyTwoCharLongAESCryptoString
  host: api-issa-payments-postgresql.db.internal
  name: api_issa_payments
  password: api_issa_payments
  port: 5432
  ssl_mode: disable
  timeout_seconds: 10
  type: postgres
  user: api_issa_payments
logs:
  access: "./logs/certavs-access.log"
  app: "./logs/certavs-application.log"
  app_level: debug