api:
  port: 8080
db:
  encryption_key: ThirtyTwoCharLongAESCryptoString
  host: localhost
  name: certavs
  password: password
  port: 5432
  ssl_mode: disable
  timeout_seconds: 10
  type: postgres
  user: certavs
logs:
  access: "./logs/certavs-access.log"
  app: "./logs/certavs-application.log"
  app_level: debug