version: '2'

services:
    db:
        build: docker/db
        environment:
            - POSTGRES_USER=certavs
            - POSTGRES_DB=certavs
            - POSTGRES_PASSWORD=password
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            # Having a named volume is enough to have persistence
            - postgresql-data:/var/lib/postgresql/data/pgdata

volumes:
    postgresql-data:
        driver: local